spring.application.name=demo
server.port=8090

# Activa el archivo local si existe
spring.profiles.include=local

# Configuración de Conexión a Base de Datos (Leída desde application-local o variables de entorno)
spring.datasource.url=${DB_URL:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
spring.sql.init.encoding=UTF-8



